#%RAML 0.8
---
title: Shipping Guide API
baseUri: https://api.bring.com/shippingguide/products

documentation:
- title: Introduction
  content: |
      The Shipping Guide (Fraktguiden) is a free service from Bring that provides

      * price information,
      * service area (norwegian: dekningsområde), and
      * estimated delivery times.

      With the Shipping Guide it is easy to offer different shipping alternatives to your end customers. Whether they want to

      * get delivery to the door (daytime or evening),
      * pick up the shipment at a post office, or
      * get the shipment delivered to the mailbox

      The Shipping Guide returns the recommended way to present these shipping alternatives, as well as prices and delivery times.

      [Demo shipping alternatives](http://fraktguide.bring.no/fraktguide/demoVelgFraktalternativ.do?from=0484&to=0470&weightInGrams=800&length=10&width=20&height=5&product=servicepakke&product=pa_doren&product=bpakke_dor-dor&product=smaapakker_a-post&product=ekspress09&product=smaapakker_b-post&product=courier_1h&product=minipakke&callbackUrl=http://fraktguide.bring.no/fraktguide/popupCallback.jsp&date=2015-10-07) form (Norwegian).

      The demo shows that the Shipping Guide returns product categories for each request, making a shipping alternatives-page easy to set up. The focus is on delivery methods to the end customer, not product names.

      The Shipping Guide has several interfaces (SOAP and XML/JSON). Choose the option that fits your needs best (see table below). The SOAP interface is the core interface with complete functionality. There are some limitations in the XML/JSON API, such as the inability to mark a parcel as a specialized goods.

      There is also a [Offline SOAP service](http://developer.bring.com/additionalresources/offlinedata.html?from=shipping) for retrieving data for offline use (get complete prices, service area and delivery times based on a fixed sender postal code).

- title: Guidelines
  content: |
      `<MainDisplayCategory>` should be written in bold text and followed by our logo. [Get approved logo here](http://mediaweb.posten.no/fotoweb/Default.fwx?archiveId=5005).

      In the webshop you should display

      * `<MainDisplayCategory>`
      * `<DisplayName>`
      * `<DescriptionText>`

      Repeat the last two as needed, depending on the number of options you would like to display.

      The following values are not meant for display in the webshop and as such should not be visible on your site

      * `<Product>`
      * `<ProductId>`
      * `<ProductCodeInProductionSystem>`

      *We strongly advise that you give your customers at least two options, home delivery and pickup point.*

      | XML | JSON/JSONP | Web services/SOAP |
      |:----|:-----------|:------------------|
      | The XML API is an easy way to integrate with the Shipping Guide using plain HTTP clients. It is also the best API to use when exploring the service using a web browser. | Web browsers can (using JavaScript) retrieve information from external sites if the data are made available in JSONP format. The purpose is that you can paste HTML / Javascript on your web page and easily use data from the Shipping Guide without server components on your web page. See widgets. | The SOAP API has the complete feature set of the Shipping Guide. It requires a SOAP client and the use of our WSDL. It has an Online version (one request per shipment) or an offline version (e.g. nightly fetch prices, service area and delivery times based on a fixed consignor postal code). |

/price{mediaTypeExtension}:
  displayName: Get shipment prices
  securedBy: [mybring_headers, null]
  description: |
      TODO: description
  uriParameters:
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to specify application/json or .xml to specify application/xml
  get:
    description: Get shipment prices
    queryParameters:
      from:
        displayName: From postal code
        type: string
        example: 7600
      to:
        displayName: To postal code
        type: string
        example: 1407
      weightInGrams:
        displayName: Weight of package in grams
        type: integer
        example: 1500
      width:
        displayName: Package width in centimeters
        type: integer
        example: 40
      length:
        displayName: Package length in centimeters
        type: integer
        example: 40
      height:
        displayName: Package height in centimeters
        type: integer
        example: 30
      date:
        displayName: Shipping date
        description: Specifies which date the parcel will be delivered to Bring (within the time limit), and is used to calculate the delivery date. Date is specified in ISO format, `YYYY-MM-DD`.
        type: date
        example: 2015-11-18
      time:
        displayName: Shipping time
        description: Shipping time may be specified. Note that Bring's courier products are the only one affected by this parameter. Time is specified in ISO format, `HH:mm`.
        type: date
        example: 12:30
      clientUrl:
        displayName: Client URL
        description: To use the Shipping Guide you must specify a client url parameter. The client url should be set to the url of the web shop or application the end user is ordering from. The client url can be sent as a url parameter, clientUrl, or as a header, `X-Bring-Client-URL`.
        type: string
        example: https://www.example.com/amazing-clothes/
      edi:
        displayName: EDI setting
        description: Flag that tells if the parcel will be registred using EDI when it is shipped. Note that this flag may affect price and which products are available.
        type: boolean
        default: true
      postingAtPostOffice:
        description: |
          Flag that tells whether the parcel is delivered at a post office when it is shipped.

          A surcharge will be applied for the following products:

          * SERVICEPAKKE
          * BPAKKE_DOR-DOR (Bedriftspakke)
        type: boolean
        default: false
      additional:
        displayName: Additional services
        description: Request additional services for the package. Specified by adding one or more `additional` parameters to the request, e.g. [&additional=postoppkrav&additional=evarsling](https://api.bring.com/shippingguide/products/SERVICEPAKKE/price.json?clientUrl=insertYourClientUrlHere&from=7600&to=1407&weightInGrams=1500&date=2009-3-27&additional=postoppkrav&additional=evarsling&additional=lordagsutkjoring). See the [additional services list](/api/product-list/#additional-services). The Shipping Guide will match the additional service codes to the requested products and ignore product / additional service codes that are not applicable.
        type: string
        example: evarsling
      priceAdjustments:
        displayName: Price adjustments
        description: Option to adjust the price returned. Specified by adding [&priceAdjustment=m20p](https://api.bring.com/shippingguide/products/SERVICEPAKKE/price.json?clientUrl=insertYourClientUrlHere&from=7600&to=1407&weightInGrams=1500&priceAdjustment=m20p). Note that price adjustments is on prices without VAT. Refer to additional examples to read more.
        type: string
        example: m20p
      pid:
        displayName: Public ID
        description: The last part (after the last dash) of your identification string (logged-in information for user of Shipping Guide). This makes the Shipping Guide know who performs the query, so we may contact the correct shipping guide user for potential follow ups.
        type: string
      product:
        displayName: Products
        description: This parameter lets you specify which products you want to return information about. If you omit this parameter, you get the default product list (not recommended for production usage). Product is specified by adding one or more product parameters, e.g. [product=servicepakke&product=bpakke_dor-dor](https://api.bring.com/shippingguide/products/price.json?clientUrl=insertYourClientUrlHere&from=7600&to=1407&weightInGrams=1500&product=servicepakke&product=bpakke_dor-dor).
        type: string
        example: bpakke_dor-dor
      language:
        displayName: Language
        description: Which language the descriptive product texts should have. Supported languages are English (en), Swedish (se), Finnish (fi), Danish (da) and Norwegian (no). If no language is set, or text is not available in the requested language, norwegian text is returned.
        type: string
        default: no
        example: en
      volumeSpecial:
        displayName: Special volume
        description: Flag to indicate if the package has a shape that may require 'special handling fee'. [product=servicepakke&product=bpakke_dor-dor](https://api.bring.com/shippingguide/products/price.json?clientUrl=insertYourClientUrlHere&from=7600&to=1407&weightInGrams=1500&product=servicepakke&product=bpakke_dor-dor&volumeSpecial=true).
        type: boolean
        default: false

    responses:
      200:
        displayName: Successful response
        body:
          application/json:
          application/xml:

/expectedDelivery{mediaTypeExtension}:
  displayName: Get estimated delivery time
  securedBy: [mybring_headers, null]
  description: |
      TODO: description
  uriParameters:
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to specify application/json or .xml to specify application/xml
  get:
    description: Get estimated delivery time
    queryParameters:
      q:
        description: Reference, package number, shipment number to search for
        type: string
        required: true
        example: TESTPACKAGE-AT-PICKUPPOINT
      callback:
        description: JSONP callback function name
        type: string
        required: false

    responses:
      200:
        displayName: Successful response
        body:
          application/json:
          application/xml:

/all{mediaTypeExtension}:
  displayName: Get shipment prices, estimated delivery and more
  securedBy: [mybring_headers, null]
  description: |
      TODO: description
  uriParameters:
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to specify application/json or .xml to specify application/xml
  get:
    description: Get shipment prices, estimated delivery and more
    queryParameters:
      q:
        description: Get shipment prices, estimated delivery time and additional information
        type: string
        required: true
        example: TESTPACKAGE-AT-PICKUPPOINT
      callback:
        description: JSONP callback function name
        type: string
        required: false

    responses:
      200:
        displayName: Successful response
        body:
          application/json:
          application/xml:


