#%RAML 1.0
---
title: Postal Code API
baseUri: https://api.bring.com/pickuppoint/api

/postalCode/{countryCode}/getCityAndType/{postalCode}{mediaTypeExtension}:
  displayName: Lookup Postal Code

  uriParameters:
    postalCode:
      displayName: Postal code
      type: string
      required: true
      example: 1337
    countryCode:
      displayName: Country
      required: true
      type: string
      default: "NO"
      example: SE
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to get application/json or .xml to get application/xml.
  get:
    description: Lookup Postal Code
    queryParameters:


    responses:
      200:
        displayName: Successful response
        body:
          application/json:
            examples:
              successful:
                displayName: Successful
                value: !include examples/response.json
          application/xml:
            examples:
              successful:
                displayName: Successful
                value: !include examples/response.xml

/postalCode/{countryCode}/getCitiesAndTypes/{postalCode}{mediaTypeExtension}:
  displayName: Lookup Postal Code having Multiple Cities

  uriParameters:
    postalCode:
      displayName: Postal code
      type: string
      required: true
      example: '01156'
    countryCode:
      displayName: Country
      required: true
      type: string
      default: "NO"
      example: DE
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to get application/json or .xml to get application/xml.
  get:
    description: Lookup Postal Code having Multiple Cities
    queryParameters:


    responses:
      200:
        displayName: Successful response
        body:
          application/json:
            examples:
              successful:
                displayName: Successful
                value: !include examples/responseForMultipleCities.json
          application/xml:
            examples:
              successful:
                displayName: Successful
                value: !include examples/responseForMultipleCities.xml

/postalCode/{countryCode}/getAllValidPostalCodes{mediaTypeExtension}:
  displayName: Lookup all postal codes for Norway, Sweden, Denmark or Finland

  uriParameters:
    countryCode:
      displayName: Country
      required: true
      type: string
      default: "NO"
      example: DE
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to get application/json or .xml to get application/xml.
  get:
    description: Lookup all postal codes for Norway, Sweden, Denmark or Finland
    queryParameters:

    responses:
      200:
        displayName: Successful response
        body:
          application/json:
            examples:
              successful:
                displayName: Successful
                value: !include examples/responseForPostalCodes.json
          application/xml:
            examples:
              successful:
                displayName: Successful
                value: !include examples/responseForPostalCodes.xml

/postalCode/{countryCode}/allValidPostalCodesDetails{mediaTypeExtension}:
  displayName: Lookup all postal codes with details for Norway, Sweden, Denmark, Finland or Svalbard and Jan Mayen

  uriParameters:
    countryCode:
      displayName: Country
      required: true
      type: string
      default: "NO"
      example: DE
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to get application/json or .xml to get application/xml.
  get:
    description: Lookup all postal codes with details for Norway, Sweden, Denmark, Finland or Svalbard and Jan Mayen
    queryParameters:

    responses:
      200:
        displayName: Successful response
        body:
          application/json:
            examples:
              successful:
                displayName: Successful
                value: !include examples/responseForPostalCodesDetails.json
          application/xml:
            examples:
              successful:
                displayName: Successful
                value: !include examples/responseForPostalCodesDetails.xml
