#%RAML 1.0
---
title: Booking API
baseUri: https://api.bring.com/booking/api

/ws:
  displayName: SOAP
  description: |
    The SOAP Body follows the same XML Schema Definition (XSD) as the XML API.

    The SOAP endpoint has the same operations as the endpoints listed above:

    - list customers
    - book shipments
    - order pickups

    ### WSDL

    [https://api.bring.com/booking/api/ws/booking-v1.wsdl](https://api.bring.com/booking/api/ws/booking-v1.wsdl)

    ### XSD

    [https://api.bring.com/booking/api/schema/booking-v1.xsd](https://api.bring.com/booking/api/schema/booking-v1.xsd)
  post:
    description: Get expected delivery, service categories and additional information.
    headers:
      Content-Type:
        description: Specify request format text/xml;charset=UTF-8
      X-MyBring-API-Uid:
        required: true
        description: Your Mybring login ID
      X-MyBring-API-Key:
        required: true
        description: Your user's API key
      X-Bring-Client-URL:
        required: true
        description: Identifying the web-page or application where the Bring API data is used
    body:
        application/xml:
          examples:
            soap_request:
              displayName: SOAP
              value: !include examples/booking_soap_request.xml

