baseURL = "https://developer.bring.com"
publishDir = "_site"
languageCode = "en-us"
title = "Bring Developer"
pluralizelisttitles = false
pygmentsUseClasses = true
summaryLength = 60
paginate = 12
ignorefiles = ["css/main.js"]
disqusShortname = "bringdev"
timeout = "60s"

[markup.highlight]
guessSyntax = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
linkify = false

[params]
description = "Documentation for developers."
ramlBuiltinTypes = [
  "any",
  "object",
  "array",
  "number",
  "boolean",
  "string",
  "date-only",
  "time-only",
  "datetime-only",
  "datetime",
  "file",
  "integer",
  "nil"
]
apis = [
  "content/api/booking/api.raml",
  "content/api/shipping-guide_2/api.raml",
  "content/api/warehousing/api.raml",
  "content/api/warehousing3/api.raml",
  "content/api/warehousing4/api.raml",
  "content/api/order-management/api.raml",
  "content/api/postal-code/api.raml",
  "content/api/event-cast/api.raml",
  "content/api/invoice/api.raml",
  "content/api/reports/api.raml",
  "content/api/shipment/api.raml",
]
examples = [
  "content/api/booking/examples/",
  "content/api/warehousing/examples/"
]

[taxonomies]
tag = "tags"

[menu]

[[menu.api]]
title = "API operational status"
url = "https://status.bring.systems"
weight = 100

[menu.api.params]
blank = "target=\"_blank\" rel=\"noopener noreferrer\""

[[menu.apidocs]]
identifier = "checkout"
title = "Checkout"
weight = 1

[[menu.apidocs]]
parent = "checkout"
title = "Checkout request builder"
url = "https://www.mybring.com/shipping-guide/integration/checkout"
weight = 15

[menu.apidocs.params]
blank = "target=\"_blank\" rel=\"noopener noreferrer\""

[[menu.apidocs]]
parent = "checkout"
identifier = "product-page-widget"
title = "Product page widget"
url = "/api/product-page-widget"
weight = 16

[[menu.apidocs]]
identifier = "book"
title = "Booking"
weight = 2

[[menu.apidocs]]
identifier = "track"
title = "Tracking"
weight = 3

[[menu.apidocs]]
identifier = "warehouse"
title = "Warehousing"
weight = 4

[[menu.apidocs]]
identifier = "rni"
title = "Reports and invoices"
weight = 5

[[menu.apidocs]]
identifier = "om"
title = "Order management"
weight = 6

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.Algolia]
vars = ["title","menu"]
params = ["excerpt"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
