- specialist: Bring Parcels, Norway
  products:
  - SERVICEPAKKE
  - EKSPRESS09
  - BPAKKE_DOR-DOR
  - PA_DOREN
  - BPAKKE_DOR-DOR_RETURSERVICE
  - EKSPRESS09_RETURSERVICE
  - SERVICEPAKKE_RETURSERVICE
  - MINIPAKKE
  - CARRYON_BUSINESS
  - CARRYON_HOMESHOPPING
  - CARRYON_BUSINESS_PALLET
  - CARRYON_BUSINESS_HALFPALLET
  - CARRYON_BUSINESS_QUARTERPALLET
  - CARRYON_BUSINESS_BULKSPLIT
  - CARRYON_BUSINESS_BULKSPLIT_0900
  - CARRYON_HOMESHOPPING_BULKSPLIT
  - CARRYON_HOMESHOPPING_BULKSPLIT_HOME
  - CARRYON_HOMESHOPPING_BULKSPLIT_MINI

- specialist: Bring International Parcels
  products:
  - CARRYON_BUSINESS_BULKSPLIT
  - CARRYON_BUSINESS_BULKSPLIT_0900
  - CARRYON_HOMESHOPPING_BULKSPLIT
  - CARRYON_HOMESHOPPING_BULKSPLIT_MINI
  - CARRYON_HOMESHOPPING_BULKSPLIT_HOME
  - CARRYON_BUSINESS_PALLET
  - CARRYON_BUSINESS_HALFPALLET
  - CARRYON_BUSINESS_QUARTERPALLET

- specialist: Bring Parcels, Denmark
  products:
  - CARRYON_BUSINESS
  - CARRYON_HOMESHOPPING
  - CARRYON_BUSINESS_PALLET
  - CARRYON_BUSINESS_HALFPALLET
  - CARRYON_BUSINESS_QUARTERPALLET
  - CARRYON_BUSINESS_BULKSPLIT
  - CARRYON_BUSINESS_BULKSPLIT_0900
  - CARRYON_HOMESHOPPING_BULKSPLIT
  - CARRYON_HOMESHOPPING_BULKSPLIT_HOME
  - CARRYON_HOMESHOPPING_BULKSPLIT_MINI

- specialist: Bring Parcels, Sweden
  products:
  - CARRYON_BUSINESS
  - CARRYON_HOMESHOPPING
  - CARRYON_BUSINESS_PALLET
  - CARRYON_BUSINESS_HALFPALLET
  - CARRYON_BUSINESS_QUARTERPALLET
  - CARRYON_BUSINESS_BULKSPLIT
  - CARRYON_BUSINESS_BULKSPLIT_0900
  - CARRYON_HOMESHOPPING_BULKSPLIT
  - CARRYON_HOMESHOPPING_BULKSPLIT_HOME
  - CARRYON_HOMESHOPPING_BULKSPLIT_MINI

- specialist: Bring Parcels, Finland
  products:
  - CARRYON_BUSINESS
  - CARRYON_HOMESHOPPING
  - CARRYON_BUSINESS_PALLET
  - CARRYON_BUSINESS_HALFPALLET
  - CARRYON_BUSINESS_QUARTERPALLET
  - CARRYON_BUSINESS_BULKSPLIT
  - CARRYON_BUSINESS_BULKSPLIT_0900
  - CARRYON_HOMESHOPPING_BULKSPLIT
  - CARRYON_HOMESHOPPING_BULKSPLIT_HOME
  - CARRYON_HOMESHOPPING_BULKSPLIT_MINI

- specialist: Bring Cargo, Norway
  products:
  - CARGO_GROUPAGE
  - CARGO

- specialist: Bring Express, Norway
  products:
  - COURIER_VIP
  - COURIER_1H
  - COURIER_2H
  - COURIER_4H
  - COURIER_6H
  - COURIER_LONG_DISTANCE
  - COURIER_BICYCLE_VIP
  - COURIER_BICYCLE_1H
  - COURIER_BICYCLE_2H
  - COURIER_BICYCLE_4H
  - QUICKPACK_SAMEDAY
  - QUICKPACK_OVER_NIGHT_0900
  - QUICKPACK_OVER_NIGHT_1200
  - QUICKPACK_DAY_CERTAIN
  - QUICKPACK_EXPRESS_ECONOMY

- specialist: Bring Express, Denmark
  products:
  - COURIER_VIP
  - COURIER_1H
  - COURIER_2H
  - COURIER_4H
  - COURIER_6H
  - COURIER_LONG_DISTANCE
  - COURIER_BICYCLE_VIP
  - COURIER_BICYCLE_1H
  - COURIER_BICYCLE_2H
  - COURIER_BICYCLE_4H
  - QUICKPACK_SAMEDAY
  - QUICKPACK_OVER_NIGHT_0900
  - QUICKPACK_OVER_NIGHT_1200
  - QUICKPACK_DAY_CERTAIN
  - QUICKPACK_EXPRESS_ECONOMY

- specialist: Bring Express, Sweden
  products:
  - COURIER_VIP
  - COURIER_1H
  - COURIER_2H
  - COURIER_4H
  - COURIER_6H
  - COURIER_LONG_DISTANCE
  - COURIER_BICYCLE_VIP
  - COURIER_BICYCLE_1H
  - COURIER_BICYCLE_2H
  - COURIER_BICYCLE_4H
  - QUICKPACK_SAMEDAY
  - QUICKPACK_OVER_NIGHT_0900
  - QUICKPACK_OVER_NIGHT_1200
  - QUICKPACK_DAY_CERTAIN
  - QUICKPACK_EXPRESS_ECONOMY

- specialist: Bring Oil Express, Norway
  products:
  - OIL_EXPRESS 
