#%RAML 1.0
---
title: Shipping Guide API
baseUri: https://api.bring.com/shippingguide

/v2/products:
  displayName: Get shipment prices and estimated delivery
  description: |
      Use this endpoint to get expected delivery, service categories and additional information.

      ### Measurements
      For cargo services(5100, 5300, 9100, CARGO), Weight is mandatory and one of the Volume / Load Meter / Dimensions / Number of Pallets is mandatory.
      
      Note: The prices for our revised services depends on volumetric weight: 5000, 5100, 5300, 5600, 5800, 4850 plus return services 9000, 9100, 9300 or 9600. For these services, dimensions (L/W/H) is needed to calculate the expected price correctly. Dimensions are also used to decide if handling fee or specialgoods fee will apply to the shipment. You might leave dimensions empty in your request, but be aware that returned prices might be incorrect.

      ### REST POST vs GET
      There is both a POST and a GET endpoint for REST. We recommend using the POST endpoint over the GET one, as this is more likely to get all new features.

  post:
    description: Get shipment prices and leadtime
    headers:
      X-MyBring-API-Uid:
        description: Your Mybring login ID
        required: true
      X-MyBring-API-Key:
        description: Your user's API key
        required: true
      Content-Type:
        description: application/json
        required: true
    body:
      application/json:
        examples:
          restEstimatedDeliveryReq:
            displayName: Estimated delivery time request
            value: !include examples/rest_estimated_delivery_time_request.json
    responses:
      200:
        body:
          application/json:
            examples:
              restEstimateDeliveryRes:
                displayName: Estimated delivery time successful response
                value: !include examples/rest_estimated_delivery_time_response_200.json

  get:
    description: Get shipment prices and leadtime
    headers:
      X-MyBring-API-Uid:
        description: Your Mybring login ID
        required: true
      X-MyBring-API-Key:
        description: Your user's API key
        required: true
      Accept:
        description: Specify request format (application/json, application/xml)
        required: true
    queryParameters:
      fromcountry:
        description: Sender country code in valid ISO Alpha-2 format.
        type: string
        example: NO
        required: true
      tocountry:
        description: Receiver country code in valid ISO Alpha-2 format.
        type: string
        example: NO
        required: true
      frompostalcode:
        description: Sender country code in valid ISO Alpha-2 format.
        type: string
        example: NO
        required: true
      topostalcode:
        description: Receiver country code in valid ISO Alpha-2 format.
        type: string
        example: NO
        required: true
      addressline:
        description: Specify address. This parameter can be maximum 35 character long. It will be for Bedriftspakke and På døren only.
        type: string
        example: Testsvingen 12
        required: false
      product:
        description: List of services requested. Multiple services can be requested in a single request. Requested service can also be specified with a customer number separated with **:** (colon) as delimiter. For example CARGO:CARGO-123456
        type: string
      date:
        description: Shipping date. For service 5600 and PA_DOREN, this date cannot be set to more than current date + 10 days if numberOfAlternativeDeliveryDates > 0.
        type: string
        example: 2018-11-18
        required: false
      time:
        description: Shipping time
        type: string
        example: "12:30"
        required: false
      weight:
        description: Package weight in grams
        type: integer
        required: false
      volumeindm3:
        description: Package volume in dm3
        type: integer
        required: false
      loadingmeter:
        description: Package loading meters
        type: double
        required: false
      width:
        description: Package width in cm
        type: integer
        required: false
      length:
        description: Package length in cm
        type: integer
        required: false
      height:
        description: Package height in cm
        type: integer
        required: false
      numberofpallets:
        displayName: Number of pallets
        type: integer
        required: false
      nonstackable:
        description: Set to true if you know that pallet would be non-stackable
        type: boolean
        required: false
        default: false
      edi:
        description: Tells if the parcel will be registered using EDI when being booked. It may affect price and which services are available
        type: boolean
        required: false
        default: true
      postingatpostoffice:
        description: |
          Tells whether the parcel is delivered at a post office when it is shipped. A surcharge will be applied for SERVICEPAKKE and BPAKKE_DOR-DOR
        type: boolean
        required: false
        default: false
      additionalservice:
        displayName: Additional service
        description: Multiple value added services can be requested by repeating this parameter
        required: false
        type: string
      customernumber:
        description: Lets you specify which customer number to use in the request. If specified and service is not supplied with delimited customer number, then it will be applied on all request services. Required if `estimateddeliverytime` is set to true.
        type: string
        example: CARGO-123456
        required: false
      language:
        description: Language used for the service texts
        type: string
        default: no
        required: false
      volumeSpecial:
        description: True if the package has a shape that requires special handling
        type: boolean
        default: false
        required: false
      incoterms:
        description: Terms of delivery
        type: string
        required: false
      unnumber:
        description: Code for dangerous goods
        type: integer
        required: false
      payer:
        description: Payer type. Possible values are SENDER, RECEIVER or THIRD_PARTY
        type: string
        required: false
      numberOfAlternativeDeliveryDates:
        description: Number of alternative delivery dates to be suggested by API for request. Maximum number is 9.
        type: integer
        required: false
      nonstandardcourierservice:
        description: Specify service code for customize courier services in the request. It will be for NonStandard Courier only.
        type: string
        example: CDA
        required: true
      estimateddeliverytime:
        description: True if you want estimated delivery time of input pickup points. Eligible services are 5800 and SERVICEPAKKE.
        type: boolean
        required: false
      uniqueAlternateDeliveryDates:
        description: True if you want unique expected delivery dates when requested with `numberofdeliverydates`.
        type: boolean
        required: false
      pickuppoints:
        description: If pickup points are specified then estimated delivery time will be added in the response for them, when `estimateddeliverytime'` flag is True. If it is not specified, then default pickup point(s) for receiver's postal code will be used. Eligible services are 5800 and SERVICEPAKKE. However we recommend to always specify pickup points for optimum results.
        type: string
        example: "171102,124518"
        required: false

    responses:
      200:
        displayName: Successful response
        description: |
          Example Request \
          [https://api.bring.com/shippingguide/v2/products?fromcountry=NO&tocountry=NO&customernumber=PARCELS_NORWAY-1234567890&frompostalcode=0165&topostalcode=1234&product=5000&product=5800:PARCELS_NORWAY-1234567990&weight=200]() \
          A successful response
      400:
        displayName: User error
        description: |
          This can mean that a required field or parameter has not been provided, the value supplied is invalid, or the combination of provided fields is invalid.
      401:
        displayName: Unauthorized
        description: |
          A failed response when the request is unauthenticated

/v2/products/price:
  displayName: Get shipment prices
  description: |
      Use this endpoint to get prices. The request parameters are the same as for [Get shipment prices and estimated delivery](/api/shipping-guide_2/#get-shipment-prices-and-estimated-delivery)
  get:
    description: Use this endpoint to get price. The request parameters are the same as for [Get shipment prices and estimated delivery](/api/shipping-guide_v2/#get-shipment-prices-and-estimated-delivery)

/v2/products/expectedDelivery:
  displayName: Get expected delivery times
  description: |
      Use this endpoint to get expected delivery. The request parameters are the same as for [Get shipment prices and estimated delivery](/api/shipping-guide_2/#get-shipment-prices-and-estimated-delivery)
  get:
    description: Get estimated delivery time

/api/ws:
  displayName: SOAP
  description: |
      The SOAP Body follows the same XML Schema Definition (XSD) as stated above.
      ### Estimated delivery times
        To get estimated delivery times in the response, set `WithExpectedDelivery` and `WithEstimatedDeliveryTime` to true in the request along with specifying `PickupPoints`
      ### Request and response structure
        If you request shipping alternatives via the API your request and response will have to comply with the following schemas:

        [https://api.bring.com/shippingguide/api/ws/shipping-guide-20.xsd](https://api.bring.com/shippingguide/api/ws/shipping-guide-20.xsd)

        [https://api.bring.com/shippingguide/api/ws/shippingguide-20.wsdl](https://api.bring.com/shippingguide/api/ws/shippingguide-20.wsdl)

  post:
    description: Use this endpoint to get same information as above REST API
    headers:
      X-MyBring-API-Uid:
        description: Your Mybring login ID
      X-MyBring-API-Key:
        description: Your user's API key
      Accept:
        description: Specify request format (application/xml)
    body:
      application/xml:
        examples:
          estimated_delivery_time_request:
            displayName: Estimated delivery time
            value: !include examples/soap_estimated_delivery_time_request.xml
    responses:
          200:
            displayName: Estimated delivery time successful response
            body:
              application/xml:
                examples:
                  estimated_delivery_time_response:
                    displayName: Estimated delivery time
                    value: !include examples/soap_estimated_delivery_time_response_200.xml
