#%RAML 1.0
title: Invoice API
baseUri: https://www.mybring.com/invoicearchive
types:
  Invoices:
    type: object
    properties:
      customerNumber:
        type: string
        required: false
        description: Represents a customerNumber
      invoiceNumber:
        type: string
        required: true
        description: Represents a invoiceNumber
      invoiceDate:
        type: string
        required: true
        description: Represents a invoice date
      invoiceIssuer:
        type: string
        required: false
        description: Represents the invoice issuer
      status:
        type: string
        required: false
        description: Represents the invoice status
      totalAmount:
        type: string
        required: false
        description: Represents the invoice total amount
      currency:
        type: string
        required: false
        description: Represents the currency used in invoice
      type:
        type: string
        required: false
        description: Represents the invoice or credit note
      dueDate:
        type: string
        required: false
        description: Represents the invoice due date
      attachmentCount:
        type: number
        required: false
        description: Represents the number of attachments associated with invoice number
      batchSource:
        type: string
        required: true
        description: Represents the invoice generated source
      invoiceSpecificationAvailable:
        type: boolean
        required: false
        description: Represents the invoice specification report available or not
      parentInvoiceNumber:
        type: string
        required: false
        description: Represents the parent invoice number

/api/invoices/{apiCustomerNumber}{mediaTypeExtension}:
  displayName: List of all Invoices
  description: Gets the list of invoices corresponding to the given customer number.
               By default it shows last 65 days of invoices, with the possibility to access last 365 days by providing "fromDate" and "toDate".
               This endpoint supports Parcel Domestic, Parcel International and Cargo customers.
  uriParameters:
    apiCustomerNumber:
      enum: [ Main customer number, EXPRESS_SWEDEN-xxxxx,EXPRESS_NORWAY-xxxxx,EXPRESS_DENMARK-xxxxx,EXPRESS_FINLAND-xxxxx]
      description: Unique API Customer Number.
    mediaTypeExtension:
      enum: [ .json, .xml ]
      description: Use .json to specify application/json or .xml to specify application/xml
  get:
    description: List of invoices
    headers:
      X-MyBring-API-Uid:
        description: Your Mybring login ID
      X-MyBring-API-Key:
        description: Your user's API key
      X-Bring-Client-URL:
        description: A URL that sort of identifies where you're using the APIs.
    queryParameters:
      fromDate:
        description: Start date for fetching invoices in format dd.mm.yyyy.
        type: string
        required: false
        example: 15.01.2020
      toDate:
        description: End date for fetching invoices in format dd.mm.yyyy.
        type: string
        required: false
        example: 25.01.2020
    responses:
      200:
        displayName: Successful response
        description:
        body:
          application/json:
            type: Invoices
            examples:
              successful:
                displayName: Successful
                description: The example below shows an list of invoices
                value: !include example/list_invoices.json
          application/xml:
            type: Invoices
            examples:
              successful:
                displayName: Successful
                description: The example below shows an list of invoices
                value: !include example/list_invoices.xml

/pdf/{apiCustomerNumber}/{invoiceNumber}.pdf:
  displayName: Invoice PDF download endpoint
  description: This link is used to download the invoice pdf for the customers by providing API customer number and invoice number in URI params.
  uriParameters:
    apiCustomerNumber:
      enum: [ Main customer number, EXPRESS_SWEDEN-xxxxx,EXPRESS_NORWAY-xxxxx,EXPRESS_DENMARK-xxxxx,EXPRESS_FINLAND-xxxxx]
      description: Unique API Customer Number.
    invoiceNumber:
      description: Invoice number of the particular invoice to be downloaded.
  get:
    description: Download pdf for invoice

