#%RAML 0.8
---
title: Easy Return Service API
baseUri: https://api.bring.com/documents/ipc/ers

documentation:
- title: Introduction
  content: |
    The API lets you create labels for parcels returning to cross-border e-retailers.

- title: Authentication
  content: |
    The Easy Return Service API requires authentication for all its endpoints. See the [getting started guide on authentication](/api/#authentication) if you're not sure what this means.

    | Header | Example | Comment |
    |:-------|:--------|:--------|
    | `X-MyBring-API-Uid` | `john.doe@example.com` | Mybring login ID |
    | `X-MyBring-API-Key` | `1234abc-abcd-1234-5678-abcd1234abcd ` | Mybring login's API key |
    | `X-Bring-Client-URL` | `https://example.com/ ` | A URL that sort of identifies where you're using the APIs. | 

    Those headers must be set for all endpoints documented below.

/label:
  displayName: Create or list labels
  post:
    description: Create new label
    queryParameters:
        CustomerId:
            description: Customer Number which Bring has provided. It cannot be demo customer number.
            type: string
            required: true
            example: 10000000000
        OrderDate:
            description: The date on which order is booked.
            type: date
            required: true
            example: 22.01.2014 11:36:22
        Sender:
            description: Details of sender. Must have Name, Street, City, CountryCode.
            required: true
        Recipient:
            description: Details of recipient. Must have Name, Street, City, CountryCode.
            required: true
        PackageId:
            description: Must be a valid parcels package ID.
            type: string
            required: true
            example: AB123456789NO
        ShipmentId:
            description: Must be numeric 17 characters (valid Posten / Bring shipment ID)
            type: integer
            required: true
            example: 70508608105602299
        CustomerReference:
            description: Any string a customer can use as reference.
            type: string
            required: false
            example: 123
        ProductCode:
            description: It is always 0341.
            type: integer
            required: true
            example: 0341
        Weight:
            description: Weight of the package.Must be between 0.1 - 20 KG.
            type: integer
            required: true
            example: 10

    body:
      application/xml:
        example: !include examples/request.xml
    responses:
      200:
        body:
          application/xml:
            example: !include examples/response.xml
  get:
    description: List previously created labels
  /{id}:
    displayName: Look up a specific label
    uriParameters:
      id:
        description: Id of the label to retrieve.
        type: string
        required: true
    get:
      description: Get label by ID
