#%RAML 0.8
---
title: Modify Delivery API
baseUri: https://www.mybring.com/modify-delivery

documentation:
- title: Introduction
  content: |
      The modify delivery api is used to modify a shipment currently on it's way.
      Below are the various modifications (which will be API calls) supported:
        - Stop shipment.
        - Change cash on deivery.
        - Change Address


- title: Authentication
  content: |
    The Modify Delivery API requires authentication. To make API requests, you will need an API key from Mybring. Steps for getting a key and description of headers can be found on the general API [Getting Started / Authentication](/api/#authentication) page.

/allowed-modification:
  displayName: Allowed modifications
  description: It gives us the list of allowed modifications on a shipment along with failure causes.

  get:
    description: List of allowed modifications, along with failure causes.
    queryParameters:
        q:
            description: Shipment number to be checked for.
            type: string
            required: true
            example: 707262014721
    responses:
      200:
        body:
          application/json:
            example: !include examples/allowed-modification.json

/stop-shipment:
  displayName: Stop shipment
  description: This will stop the shipment and send it back to the sender .
  post:
    description: Stop a shipment and return to sender.
    body:
      application/json:
        example: !include examples/stoprequest.json

    responses:
      200:
        body:
          application/xml:
            example: !include examples/stopresponse.json

/change-cod:
  displayName: Change cash on delivery
  description: This is used the change the COD amount on the shipment .

  post:
    description: Change cash on delivery amount to be paid.
    body:
      application/json:
        example: !include examples/changecodrequest.json

    responses:
      200:
        body:
          application/json:
            example: !include examples/changecodresponse.json

/modifications/{shipmentNumber}/address:
  displayName: Change recipient address of delivery.
  description: This is used to change the recipient delivery address .
  uriParameters:
    shipmentNumber:
      description: Shipment number to change address for.
      type: string
      required: true
      example: 707262014721

  post:
    description: Change recipient address of delivery.
    body:
      application/json:
        example: !include examples/changeAddressRequest.json

    responses:
      200:
        body:
          application/json:
            example: !include examples/changeAddressResponse.json


/modifications/changeAddress/price/{shipment}/{oldPostal}/{newPostal}:
  displayName: Get price for change address.
  description: Get the cost for changing address on a shipment.

  uriParameters:
    shipment:
      description: Shipment number.
      type: string
      required: true
      example: 707262014721
    oldPostal:
      description: Current postal code of recipient address.
      type: string
      required: true
      example: 0021
    newPostal:
      description: New postal code to where shipment will be re-routed to.
      type: string
      required: true
      example: 0484

  get:
    description: Get the cost for changing address on a shipment.
    responses:
      200:
         body:
           application/json:
             example: !include examples/changeAddressCost.json

/modifications/fetchChangeAddressData/{shipmentNumber}:
  displayName: Current recipient address
  description: Get the current recipient address on the shipment.

  uriParameters:
    shipmentNumber:
      description: Shipment number to get current recipient address.
      type: string
      required: true
      example: 707262014721

  get:
    description: Get current recipient address for shipment.
    responses:
      200:
         body:
           application/json:
             example: !include examples/changeAddressRecipientData.json

/modifications/customer/{customerNumber}:
  displayName: Get modifications history.
  description: Get list of all the shipments for the customer number on which COD, STOP Delivery and Change address have been done.

  uriParameters:
    customerNumber:
      description: Customer number.
      type: string
      required: true

  get:
    description: Get history for all the modifications done for a customer
    responses:
      200:
         body:
           application/json:
             example: !include examples/changeAddressHistoryData.json
