#%RAML 1.0
---
title: Modify Delivery API
baseUri: https://www.mybring.com/modify-delivery

documentation:
- title: Introduction
  content: |
      The modify delivery api is used to modify a shipment currently on it's way.
      Below are the various modifications (which will be API calls) supported:
        - Stop shipment.
        - Change cash on deivery.
        - Change Address


- title: Authentication
  content: |
    The Modify Delivery API requires authentication. To make API requests, you will need an API key from Mybring. Steps for getting a key and description of headers can be found on the general API [Getting Started / Authentication](/api/#authentication) page.

- title: Common Criteria
  content: |
    To successfully modify a delivery, the shipment must have both sender and recipient address located in Norway. Additionally, any of the following events should not be present on the shipment:
      - Damaged
      - Deviation
      - Returned
      - Delivered
      - Lost
      - Partly delivered
      - Stop Shipment

- title: Service overview
  content: |
   The table shows currently supported services and the corresponding usage for modifiy delivery APIs.
   <table style = "width 100%">
     <thead>
      <tr>
        <th style="text-align: left">Service</th>
        <th style="text-align: left">Service code</th>
        <th style="text-align: left">Stop shipment</th>
        <th style="text-align: left">Change COD</th>
        <th style="text-align: left">Change Address</th>
      </tr>
     </thead>
     <tbody>
       <tr>
          <td>Bedriftspakke Dør - Dør Innland</td>
          <td>1000</td>
          <td>Yes</td>
          <td>Yes</td>
          <td>Yes</td>
       </tr>
       <tr>
          <td>Bedriftspakke ekspress over natten</td>
          <td>1002</td>
          <td>Yes</td>
          <td>Yes</td>
          <td>No</td>
       </tr>
       <tr>
          <td>Klimanøytral Servicepakke</td>
          <td>1202</td>
          <td>Yes</td>
          <td>Yes</td>
          <td>Yes</td>
       </tr>
       <tr>
          <td>På Døren</td>
          <td>1736</td>
          <td>Yes</td>
          <td>Yes</td>
          <td>Yes</td>
       </tr>
       <tr>
          <td>Konv Bedriftspakke Flerkolli</td>
          <td>1988</td>
          <td>Yes</td>
          <td>Yes</td>
          <td>Yes</td>
       </tr>
       <tr>
          <td>Bedriftspakke Standard</td>
          <td>3500</td>
          <td>Yes</td>
          <td>Yes</td>
          <td>No</td>
       </tr>
       <tr>
          <td>Ekspress neste dag</td>
          <td>4850</td>
          <td>Yes</td>
          <td>No</td>
          <td>No</td>
       </tr>
       <tr>
          <td>Pakke til bedrift</td>
          <td>5000</td>
          <td>Yes</td>
          <td>No</td>
          <td>Yes</td>
       </tr>
       <tr>
          <td>Pakke levert hjem</td>
          <td>5600</td>
          <td>Yes</td>
          <td>No</td>
          <td>Yes</td>
       </tr>
       <tr>
          <td>Pakke til hentested</td>
          <td>5800</td>
          <td>Yes</td>
          <td>Yes</td>
          <td>Yes</td>
       </tr>

     </tbody>
   </table>

/allowed-modification:
  displayName: Allowed modifications
  description: It gives us the list of allowed modifications on a shipment along with failure causes.

  get:
    description: List of allowed modifications, along with failure causes.
    queryParameters:
        q:
            description: Shipment number to be checked for.
            type: string
            required: true
            example: "707262014721"
    responses:
      200:
        body:
          application/json:
            examples:
              allowed_mods:
                displayName: Allowed modifications
                value: !include examples/allowed-modification.json

/stop-shipment:
  displayName: Stop shipment
  description: |
    This will stop the shipment and send it back to the sender.

  post:
    description: Stop a shipment and return to sender.
    body:
      application/json:
        examples:
          stop_shipment:
            displayName: Stop shipment
            value: !include examples/stoprequest.json

    responses:
      200:
        body:
          application/json:
            examples:
              stop_shipment:
                displayName: Stop shipment
                value: !include examples/stopresponse.json

/change-cod:
  displayName: Change cash on delivery
  description: |
    This is used to change the COD amount on the shipment.

    ### Criteria
    The shipment must have "Betaling ved utlevering (COD)" with VAS-Code 1000 registered.

  post:
    description: Change cash on delivery amount to be paid.
    body:
      application/json:
        examples:
          change_cod:
            displayName: Change cash on delivery
            value: !include examples/changecodrequest.json

    responses:
      200:
        body:
          application/json:
            examples:
              change_cod:
                displayName: Change cash on delivery
                value: !include examples/changecodresponse.json

/modifications/changeAddress/price/{shipment}/{oldPostal}/{newPostal}:
  displayName: Get price for change address
  description: |
    Get the cost for changing address on a shipment. Currently the price for changing address is a fixed amount. It will
    give exactly the same amount as in the example below.

  uriParameters:
    shipment:
      description: Shipment number.
      type: string
      required: true
      example: "707262014721"
    oldPostal:
      description: Current postal code of recipient address.
      type: string
      required: true
      example: "0021"
    newPostal:
      description: New postal code to where shipment will be re-routed to.
      type: string
      required: true
      example: "0484"

  get:
    description: Get the cost for changing address on a shipment.
    responses:
      200:
        body:
          application/json:
            examples: 
              change_cost:
                displayName: Price for address change
                value: !include examples/changeAddressCost.json

/modifications/{shipmentNumber}/address:
  displayName: Change recipient address of delivery
  description: |
   This is used to change the recipient delivery address.

   ### Criteria

   The following events should not be present on the shipment:
    - Loaded for Delivery
    - Partly delivered due to damage
    - Home delivery ordered by recipient

   The shipment must not have any of the following VAS registered:
    - Alternativt utleveringssted (0010)
    - Mottakerbestilt hjemlevering (1158, 1159)

  uriParameters:
    shipmentNumber:
      description: Shipment number to change address for.
      type: string
      required: true
      example: "707262014721"

  post:
    description: Change recipient address of delivery.
    body:
      application/json:
        examples:
          change_recipient:
            displayName: Change recipient address
            value: !include examples/changeAddressRequest.json

    responses:
      200:
        body:
          application/json:
            examples:
              change_recipient:
                displayName: Change recipient address
                value: !include examples/changeAddressResponse.json

/modifications/fetchChangeAddressData/{shipmentNumber}:
  displayName: Current recipient address
  description: Get the current recipient address on the shipment.

  uriParameters:
    shipmentNumber:
      description: Shipment number to get current recipient address.
      type: string
      required: true
      example: "707262014721"

  get:
    description: Get current recipient address for shipment.
    responses:
      200:
        body:
          application/json:
            examples:
              current_recipient:
                displayName: Current recipient address
                value: !include examples/changeAddressRecipientData.json

/modifications/customer/{customerNumber}:
  displayName: Get modifications history
  description: Get list of all the shipments for the customer number on which COD, STOP Delivery and Change address have been done.

  uriParameters:
    customerNumber:
      description: Customer number.
      type: string
      required: true

  get:
    description: Get history for all the modifications done for a customer
    responses:
      200:
        body:
          application/json:
            examples: 
              mod_history:
                displayName: Modification history
                value: !include examples/changeAddressHistoryData.json
