#%RAML 1.0
---
title: Order Management API
baseUri: https://api.bring.com/po/api/v1

/purchaseorderCustomer/{customerId}:
  displayName: Check if customer is valid for order management
  description: |
      Check if a given customer number is allowed to use Order management functionalities.
  get:
    description:
     Check if customer is valid for order management
    responses:
      200:
        displayName: Success
        description: |
          Returns `true` if given customer is a valid for order management.
        body:
          application/xml:
            examples:
              success:
                displayName: Check if customer is valid
                value: !include examples/verify_customer.xml
          application/json:
            examples: 
              success:
                displayName: Check if customer is valid
                value: !include examples/verify_customer.json

/omorder/{customerId}/{orderId}:
  displayName: Provide order information
  description: |
      Get all information on a given order and customer. Order is unique in combination with customer number.
  get:
    description: Provide order information
    responses:
      200:
        displayName: Success
        description: |
          Complete order information including order items.
        body:
          application/xml:
            examples:
              retrieve_order:
                displayName: Provide order information
                value: !include examples/retrieve_order.xml
          application/json:
            examples: 
              retrieve_order:
                displayName: Provide order information
                value: !include examples/retrieve_order.json

/items/{customerId}/{orderId}:
  displayName: List order lines
  description: |
      List all item lines that is ordered on an order.
  get:
    description: List order lines
    responses:
      200:
        displayName: Success
        description: |
          List of order items.
        body:
          application/xml:
            examples:
              retrieve_orderitems:
                displayName: List order lines
                value: !include examples/retrieve_orderitems.xml
          application/json:
            examples:
              retrieve_orderitems:
                displayName: List order lines
                value: !include examples/retrieve_orderitems.json

/packaginglist/{customerId}/{orderId}:
  displayName: Provide packaging list information for the order
  description: |
      List all packaging list information for this order. One order can have multiple packaging lists.
  get:
    description: Provide packaging list information for the order
    responses:
      200:
        displayName: Success
        description: |
          List of packaging list for given order, if any.
        body:
          application/xml:
            examples:
              retrieve_packinglist:
                displayName: Packaging list information
                value: !include examples/retrieve_packinglist.xml
          application/json:
            examples: 
              retrieve_packinglist:
                displayName: Packaging list information
                value: !include examples/retrieve_packinglist.json

/packaginglist:
  displayName: Add packaging list
  description: |
      When an order have been picked and sent, add packing list on order with transport information.
  post:
    description: Add packaging list
    body:
      application/xml:
        examples:
          add_packaging_list:
            displayName: Add packaging list
            value: !include examples/create_packaging_list.xml
    responses:
      200:
        displayName: Success
        description: |
          Successfully added packaging list.

/senderStatus/{customerId}/{orderId}:
  displayName: Get status for order (delivered/locked)
  description: |
      Check sender status for an order. Open when not fully delivered or locked when fully delivered.
  get:
    description: Get status for order (delivered/locked)
    responses:
      200:
        displayName: Success
        description: Open or Locked.
        body:
          application/xml:
            examples:
              check_status:
                displayName: Get status for order
                value: !include examples/check_status.xml
          application/json:
            examples: 
              check_status:
                displayName: Get status for order
                value: !include examples/check_status.json

/event:
  displayName: Create TMSEvents
  description: |
      Create tracking events on transports associated with orders in Order Management.
  post:
    description: Create TMSEvents
    body:
      application/xml:
        examples:
          create_events:
            displayName: Create TMSEvents
            value: !include examples/create_events.xml
    responses:
      200:
        displayName: Success
        description: |
          Successfully created a new resource

/errorCodes:
  displayName: List error codes
  get:
    description: List error codes
    responses:
      200:
        displayName: Success
        description: |
          Dynamic list of error codes used in the solution.
        body:
          application/xml:
            examples:
              error_codes:
                displayName: List error codes
                value: !include examples/error_codes.xml
          application/json:
            examples: 
              error_codes:
                displayName: List error codes
                value: !include examples/error_codes.json
