#!/usr/bin/env node

var raml = require('raml-1-parser');
var fs = require('fs');
var path = require('path');

var args = process.argv.slice(2);

if (args.length < 2) {
  console.log('Must provide input RAML file and output HTML file');
  process.exit(1);
}

var raml_file = path.resolve(args[0]);
var html_file = path.resolve(args[1]);

var api = raml.loadApiSync(raml_file);
console.log(JSON.stringify(api.toJSON(), null, 2));
