#!/usr/bin/env node

const raml = require("raml-1-parser");
const fs = require("fs");
const join = require("path").join;
const hrstart = process.hrtime();
const hrend = process.hrtime(hrstart);

const outdir = join(__dirname, "../data");
const config = require(join(__dirname, "../hugo.json"));
const filePaths = config.params.ramlSrc;

if (!fs.existsSync(outdir)) {
  fs.mkdirSync(outdir);
}
const fileOut = join(outdir, "/ramlsrc.json");

let apiArray = [];

filePaths.forEach((filePath, i) => {
  const regEx = /content\/api\/(\S*)\/api.raml/;
  const pathRegEx = filePath.match(regEx);
  let apiObjectName = pathRegEx[1];
  if (apiObjectName.includes("-")) {
    apiObjectName = apiObjectName.replace("-", "");
  }
  const apiFile = join(__dirname, "../" + filePath);
  const api = raml.loadApiSync(apiFile);
  let apiObject;
  if (i == 0) {
    apiObject =
      '{\n"' + apiObjectName + '": ' + JSON.stringify(api.toJSON(), null, 2);
  } else if (i == filePaths.length - 1) {
    apiObject =
      '\n"' +
      apiObjectName +
      '": ' +
      JSON.stringify(api.toJSON(), null, 2) +
      "\n}";
  } else {
    apiObject =
      '\n"' + apiObjectName + '": ' + JSON.stringify(api.toJSON(), null, 2);
  }
  apiArray.push(apiObject);
});

fs.writeFileSync(fileOut, apiArray.toString(), "utf-8");
console.info("JSON generated in: %dms", hrend[1] / 1000000);
