#%RAML 0.8
---
title: Invoice API
baseUri: https://www.mybring.com

documentation:
- title: Introduction
  content: |
      The Invoice API is used to download the invoice pdfs same as in Mybring.

- title: Authentication
  content: |
    The Invoice API requires authentication for all its endpoints. See the [getting started guide on authentication](/api/#authentication) if you're not sure what this means.


    | Header | Example | Comment |
    |:-------|:--------|:--------|
    | `X-MyBring-API-Uid` | `john.doe@example.com` | Mybring login ID |
    | `X-MyBring-API-Key` | `1234abc-abcd-1234-5678-abcd1234abcd ` | Mybring login's API key |
    | `X-Bring-Client-URL` | `https://example.com/ ` | A URL that sort of identifies where you're using the APIs. |

    Those headers must be present for authenticating requests.

/invoicearchive/pdf/{customerNumberUnique}/{invoiceNumber}.pdf:
  displayName: Invoice PDF download endpoint
  securedBy: [mybring_headers, null]
  description: |
      This link is used to download the invoice pdf for the customers by providing API Customer Id and invoice number in URI params.


  uriParameters:
    customerNumberUnique:
      description: Unique API Customer Number for each customer.
    invoiceNumber:
      description: Invoice number of the particular invoice to be downloaded.

  get:
    description: Download pdf for invoice

/reports/api/invoices/{customerOrGroupId}{mediaTypeExtension}:
  displayName: List of all Invoices
  description: |
    Use the existing [Reports Api List invoice numbers](/api/reports/#list-invoice-numbers) for this feature. Gets the list of invoice numbers for a customer id or a customer group. By default it shows last 65 days of invoices, with the possibilty to access 365 days data by providing from date and to date.
  uriParameters:
      customerOrGroupId:
        description: Id for customer or customer group. Customer group id should have the prefix `GROUP_` e.g. GROUP_12345
        type: string
        required: true
      mediaTypeExtension:
        enum: [ .json, .xml ]
        description: Use .json to specify application/json or .xml to specify application/xml

  get:
    description: List invoice numbers
    queryParameters:
      fromDate:
        description: Start date for fetching invoices in format dd.mm.yyyy.
        type: string
        required: false
        example: 01.01.2019
      toDate:
        description: End date for fetching invoices in format dd.mm.yyyy.
        type: string
        required: false
        example: 30.06.2019


/invoicearchive/api/invoices/{customerNumberUnique}{mediaTypeExtension}:
  displayName: List of all Invoices (NEW)
  description: |
    Gets the list of invoices corresponding to the given customer number. By default it shows last 65 days of invoices, with the possibilty to access for 365 days of invoice by providing "fromDate" and "toDate". This endpoint supports Parcel Norway, Parcel International and Cargo customers.
  uriParameters:
      customerNumberUnique:
        description: Unique API Customer Number for each customer.
        type: string
        required: true
      mediaTypeExtension:
        enum: [ .json, .xml ]
        description: Use .json to specify application/json or .xml to specify application/xml

  get:
    description: List invoice numbers
    queryParameters:
      fromDate:
        description: Start date for fetching invoices in format dd.mm.yyyy.
        type: string
        required: false
        example: 01.01.2019
      toDate:
        description: End date for fetching invoices in format dd.mm.yyyy.
        type: string
        required: false
        example: 30.01.2019
