#%RAML 0.8
---
title: Modify Delivery API
baseUri: https://www.mybring.com/modify-delivery

documentation:
- title: Introduction
  content: |
      The modify delivery api is used to modify a shipment currently on it's way.
      Below are the various modifications (which will be API calls) supported:
        - Stop shipment.
        - Change cash on deivery.
        - Change Address


- title: Authentication
  content: |
    The Modify delivery API requires authentication for all its endpoints. See the [getting started guide on authentication](/api/#authentication) if you're not sure what this means.

    | Header | Example | Comment |
    |:-------|:--------|:--------|
    | `X-MyBring-API-Uid` | `john.doe@example.com` | Mybring login ID |
    | `X-MyBring-API-Key` | `1234abc-abcd-1234-5678-abcd1234abcd ` | Mybring login's API key |
    | `X-Bring-Client-URL` | `https://example.com/ ` | A URL that sort of identifies where you're using the APIs. |

    Those headers must be present for authenticating requests.

/allowed-modification:
  displayName: Allowed modifications
  get:
    description: List of allowed modifications, along with failure causes.
    queryParameters:
        q:
            description: Shipment number to be checked for.
            type: string
            required: true
            example: 707262014721
    responses:
      200:
        body:
          application/json:
            example: !include examples/allowed-modification.json

/stop-shipment:
  displayName: Stop shipment

  post:
    description: Stop a shipment and return to sender.
    body:
      application/json:
        example: !include examples/stoprequest.json

    responses:
      200:
        body:
          application/xml:
            example: !include examples/stopresponse.json

/change-cod:
  displayName: Change cash on delivery

  post:
    description: Change cash on delivery amount to be paid.
    body:
      application/json:
        example: !include examples/changecodrequest.json

    responses:
      200:
        body:
          application/json:
            example: !include examples/changecodresponse.json

/modifications/{shipmentNumber}/address:
  displayName: Change address of delivery

  uriParameters:
    shipmentNumber:
      description: Shipment number to change address for .
      type: string
      required: true
      example: 707262014721

  post:
    description: Change address of delivery .
    body:
      application/json:
        example: !include examples/changeAddressRequest.json

    responses:
      200:
        body:
          application/json:
            example: !include examples/changeAddressResponse.json


/modifications/changeAddress/price/{shipmentNumber}/{currentPostalCode}/{newPostalCode}:
  displayName: Get price for change address
  description: Get the cost for changing address on a shipment.

  uriParameters:
    shipmentNumber:
      description: Shipment number .
      type: string
      required: true
      example: 707262014721
    currentPostalCode:
      description: Current postal code of recipient address.
      type: string
      required: true
      example: 0021
    newPostalCode:
      description: New postal code to where shipment will be re-routed to .
      type: string
      required: true
      example: 0484

  get:
    description: Get price for change address .
    responses:
      200:
         body:
           application/json:
             example: !include examples/changeAddressCost.json

/modifications/fetchChangeAddressData/{shipmentNumber}:
  displayName: Current recipient address
  description: Get the current recipient address on the shipment.

  uriParameters:
    shipmentNumber:
      description: Shipment number to get current recipient address.
      type: string
      required: true
      example: 707262014721

  get:
    description: Get current recipient address for shipment
    responses:
      200:
         body:
           application/json:
             example: !include examples/changeAddressRecipientData.json
